### ISSUE TITLE
What exactly am i suppose to put in the password?

### ISSUE THREAD

**Issue by tripper-app** [hpats/bumapi#2]
How do i get my password? At no point i had to pick any

**Comment by hpats** [comment]
You need to create an account using your mobile phone. Basically you should not use Facebook or Apple etc to sign in.
Once you create an account using your mobile phone you will have the option to create a password.

**Comment by tripper-app** [comment]
if i already created an account using facebooks what should i do?

**Comment by hpats** [comment]
I haven't found a way to use the Facebook account as login. I'm sure there is some way to do it but I havent tried it. Maybe try to create a test account using your mobile phone and then migrate your main account to the new account.
